export const initialSimulatorState = {
  simulatorMode: 'gasoline_hybrid',
  cars: [],
  activeView: 'intro',
  selectedCarId: '',
  distance: 10000,
  gasPrice: 170,
  insurance: 80000,
  parking: 5000,
  inspection: 100000,
  ownershipYears: 5,
  fuel: '',
  engine: '',
  price: '',
  result: null,
  loading: false,
  error: null,
  importMessage: null,
  importLoading: false,
  selectedMaker: '',
  /** gasoline_hybrid 専用（CSVの powertrain: gasoline / hybrid） */
  gasolinePowertrain: '',
  /** plugin_ev 専用（bev / phev / fcv、未選択は ''） */
  powertrain: '',
  electricWhPerKm: '',
  hydrogenKmPerKg: '',
  electricityPrice: 27,
  hydrogenPrice: 1200,
  phevEvRatio: 0.5,
  comparisonItems: [],
}
