export const initialSimulatorState = {
  cars: [],
  activeView: 'intro',
  selectedCarId: '',
  distance: 10000,
  gasPrice: 170,
  insurance: 80000,
  parking: 5000,
  inspection: 100000,
  ownershipYears: 5,
  fuel: '',
  engine: '',
  price: '',
  result: null,
  loading: false,
  error: null,
  importMessage: null,
  importLoading: false,
  selectedMaker: '',
}
